base_url = "https://MartinMikkelsen.github.io/"      # Domain name of your website
title = "Martin Mikkelsen"
description = "PhD student @ University of Copenhagen"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false # Keep this false, as it may cause issues with some styles
build_search_index = false # Keep this false, search is temporarily unsupported
generate_feeds = false # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filenames = ["feed.xml"] # "feed.xml" | "atom.xml" | "rss.xml", read docs for more info
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "Martin Mikkelsen"
id = "Martin"
bio = "PhD student @ University of Copenhagen"
avatar = "img/avatar.webp"

display_id = false
display_bio = true
display_avatar = false

recent = false
recent_max = 5
recent_more_text = "more »"

sections = [
    { name = "Posts", path = "/posts", is_external = false },
     { name = "Publications", path = "/projects", is_external = false },
    { name = "CV", path = "/about", is_external = false },
    # { name = "github", path = "https://github.com/<your-username>", is_external = true },
]
blog_section_path = "/posts"

back_link_text = "Back" # Text of the back button

links = [
    { name = "GitHub", icon = "github", url = "https://github.com/MartinMikkelsen" },
    { name = "Google Scholar", icon = "cap", url = "https://scholar.google.com/citations?user=oLo9mS0AAAAJ&hl=da" },
    { name = "Email", icon = "email", url = "mailto:MartinMikkelsen@proton.me" },
    { name = "LinkedIn", icon = "linkedin", url = "https://www.linkedin.com/in/martinmikkelsen1/" }
]

nav_wrapper_left = "<div class='nav-left'>"
nav_wrapper_right = "</div>"
nav_wrapper_separator = "|"
nav_separator = "|"
outdate_alert = false # Set to true if you want to enable outdated content alerts
outdate_alert_days = 365 # Set the number of days after which a post is considered outdated
force_theme = false                   # false | "light" | "dark"
blog_categorized = true               # Whether to categorize blog posts
blur_effect = true                   # Whether to turn on blur effect on navigation bar
back_to_top = true                    # Whether to show back-to-top button on post pages
toc = true                            # Whether to show Table-of-Contents by default
copy = true                           # Whether to add a copy button on code blocks by default
display_tags = true                   # Whether to display tags on post pages by default
truncate_summary = false              # Whether to truncate the summary of a post by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info

reaction = false                      # Whether to show anonymous reactions (Note: You need to set up a working api endpoint to enable anonymous reaction)
reaction_align = "right"              # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"


footer_copyright = "© 2025 Martin Mikkelsen"

not_found_title = "404"
not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"
